# Zgony według lat (roczne sumy), GUS
## W podziale na powiaty, płeć i 5-letnie grupy wiekowe

Potrzebne funkcje w plikach:
* helper_functions.py
* govpl_function.py

In [1]:
"""
Set PYTHONPATH for modules in parallel directory

https://stackoverflow.com/questions/3108285/in-python-script-how-do-i-set-pythonpath/3108301

"""

import sys

try:
    sys.path.index('..') # Or os.getcwd() for this directory
except ValueError:
    sys.path.append('..') # Or os.getcwd() for this directory

#--------------------------------------------------------------

from share.helper_functions import (
    getfile, 
    unzip, 
    xlsx2xls, 
    display_all,
    set_legend_right,
    plot

)
from typing import NamedTuple
from share.gus_functions import (
    GUSparams,
    Analysis
    )
# import govpl_functions as govpl
import pandas as pd
import importlib
import glob
import os
from sorcery import dict_of
import matplotlib.pyplot as plt

In [2]:
params = dict_of(
    data_dir = './gus_data',
    img_dir = './images',
    url =\
    'https://stat.gov.pl/download/gfx/portalinformacyjny/pl/defaultaktualnosci/5468/39/2/1/zgony_wg_tygodni.zip',
    zipfile = 'zgony_wg_tygodni.zip',
    file_prefix = 'Zgony wedêug tygodni w Polsce_',
    file_prefix_terminal = 'Zgony\ wedêug\ tygodni\ w\ Polsce_',
    file_suffix = '.xlsx',
    libreoffice_cmd = 'libreoffice7.2',
    year_start = 2000,
    year_end = 2021
)

In [3]:
mygus = Analysis(params)

In [4]:
# os.system("rm -r ./gus_data/zgony_wg_tygodni")
# os.system("rm ./gus_data/Zgony\ wedêug\ tygodni\ w\ Polsce_.csv")
# os.system("rm ./gus_data/zgony_wg_tygodni.zip")

In [6]:
mygus.getdata('KOBIETY')

Getting GUS data...
Downloading file: https://stat.gov.pl/download/gfx/portalinformacyjny/pl/defaultaktualnosci/5468/39/2/1/zgony_wg_tygodni.zip
Unzipping file: zgony_wg_tygodni.zip
Converting *.xlsx to *.xls
2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021
Making dictionary of year GUS data frames for each year: year_data_dict {int : pandas.DataFrame}
2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021
Merging GUS data frames from dict in a single data frame: all_years_df
Saving GUS data frame for all years as ./gus_data/Zgony wedêug tygodni w Polsce_.csv
Done.

In [10]:
dfp = mygus.all_years_df

In [11]:
dfK = dfp[(dfp['NUTS'].str.len()==5)&(dfp['Wiek zmarłych w latach'] != 'Ogółem')].copy(deep=True)

In [14]:
numlist = range(1,54)
collist = [f"T{x:02d}" for x in numlist]
dfK['Rocznie'] = dfK[collist].sum(axis=1) 
# dfK

In [15]:
dfK.to_csv('./gus_data/zgony_kobiety_lata.csv', index=False)

In [18]:
os.system("rm -r ./gus_data/zgony_wg_tygodni")
os.system("rm ./gus_data/Zgony\ wedêug\ tygodni\ w\ Polsce_.csv")
os.system("rm ./gus_data/zgony_wg_tygodni.zip")

0

In [19]:
mygus.getdata('MĘŻCZYŹNI')
dfp = mygus.all_years_df
dfM = dfp[(dfp['NUTS'].str.len()==5)&(dfp['Wiek zmarłych w latach'] != 'Ogółem')].copy(deep=True)
numlist = range(1,54)
collist = [f"T{x:02d}" for x in numlist]
dfM['Rocznie'] = dfM[collist].sum(axis=1) 
dfM.to_csv('./gus_data/zgony_mezczyzni_lata.csv', index=False)

Getting GUS data...
Downloading file: https://stat.gov.pl/download/gfx/portalinformacyjny/pl/defaultaktualnosci/5468/39/2/1/zgony_wg_tygodni.zip
Unzipping file: zgony_wg_tygodni.zip
Converting *.xlsx to *.xls
2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021
Making dictionary of year GUS data frames for each year: year_data_dict {int : pandas.DataFrame}
2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021
Merging GUS data frames from dict in a single data frame: all_years_df
Saving GUS data frame for all years as ./gus_data/Zgony wedêug tygodni w Polsce_.csv
Done.

In [20]:
dfM

,Rok,Wiek zmarłych w latach,NUTS,Podregiony,T01,T02,T03,T04,T05,T06,...,T45,T46,T47,T48,T49,T50,T51,T52,T53,Rocznie
101,2000,0 - 4,PL213,Miasto Kraków,1,1,1,0,1,1,...,2,0,1,1,1,1,0,0,NaN,27.0
102,2000,0 - 4,PL214,Krakowski,1,0,0,1,1,1,...,0,1,0,0,2,1,1,1,NaN,29.0
103,2000,0 - 4,PL217,Tarnowski,1,0,0,0,0,0,...,1,0,0,0,1,0,1,0,NaN,20.0
104,2000,0 - 4,PL218,Nowosądecki,1,3,1,2,1,1,...,1,1,0,0,1,1,1,0,NaN,42.0
105,2000,0 - 4,PL219,Nowotarski,0,0,1,0,0,1,...,0,0,0,1,0,1,0,0,NaN,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43115,2021,90 i więcej,PL922,Ciechanowski,6,5,4,6,4,4,...,4,4,5,5,4,4,4,5,NaN,172.0
43116,2021,90 i więcej,PL923,Płocki,4,3,5,3,3,2,...,3,2,5,3,4,10,4,2,NaN,146.0
43117,2021,90 i więcej,PL924,Ostrołęcki,4,6,5,5,1,4,...,8,8,8,4,7,6,3,8,NaN,232.0
43118,2021,90 i więcej,PL925,Siedlecki,4,2,9,7,4,9,...,9,10,14,13,4,8,2,6,NaN,272.0
43119,2021,90 i więcej,PL926,Żyrardowski,2,2,0,2,5,2,...,3,2,4,5,4,4,2,3,NaN,137.0

In [12]:
# # %load_ext autoreload
# # %autoreload

# # from share.helper_functions import (
# #     getfile, 
# #     unzip, 
# #     xlsx2xls, 
# #     display_all,
# #     set_legend_right,
# #     plot
# # )

# wiek = 'Ogółem'
# podregion = 'Lubelskie'
# Q = f'(`Wiek zmarłych w latach` == "{wiek}")  & (Podregiony == "{podregion}")'
# df = mygus.all_years_df.query(Q)



# plotopts = dict_of(
#     plotdf=df.iloc[:, 4:].T,
#     ylabel = 'Zgony',
#     title = f'Wiek: {wiek}, podregion: {podregion}',
#     fontsize = 12,
#     legendlabels = df['Rok'].to_list()
#     )

# plot(**plotopts);

In [22]:
# mygus.all_years_df['Podregiony'][80:100]

In [13]:
# wiek = 'Ogółem'
# podregion1 = 'Lubelskie'
# podregion2 = 'Makroregion Województwo Mazowieckie'
# podregion3 = 'Podkarpackie'
# Q = f'(`Wiek zmarłych w latach` == "{wiek}")  & ((Podregiony == "{podregion1}") | (Podregiony == "{podregion2}")| (Podregiony == "{podregion3}")) & (Rok > 2019)'
# df = mygus.all_years_df.query(Q)

# display(df)


# p = df['Podregiony'].tolist()
# r = df['Rok'].tolist()
# legendlabels=[]
# for i in range(0,df.shape[0]):
#     legendlabels.append( p[i] + ', ' + str(r[i]))

# plotopts = dict_of(
#     plotdf=df.iloc[:, 4:].T,
#     ylabel = 'Zgony',
#     title = f'Wiek: {wiek}, podregion: {podregion1}, {podregion2}, {podregion3}',
#     fontsize = 12,
#     legendlabels = legendlabels
#     )

# plot(**plotopts);