In [1]:
"""
Set PYTHONPATH for modules in parallel directory

https://stackoverflow.com/questions/3108285/in-python-script-how-do-i-set-pythonpath/3108301

"""

import sys

try:
    sys.path.index('..') # Or os.getcwd() for this directory
except ValueError:
    sys.path.append('..') # Or os.getcwd() for this directory

#--------------------------------------------------------------
import pandas as pd
import datetime
import numpy as np

In [2]:
url = "https://www.arcgis.com/sharing/rest/content/items/153a138859bb4c418156642b5b74925b/data"
data_dir = './MZ_data'

In [7]:
df=pd.read_csv(url, encoding = 'cp1250', sep = ';',low_memory=False)
df

,wojewodztwo,liczba_przypadkow,liczba_na_10_tys_mieszkancow,zgony,zgony_w_wyniku_covid_bez_chorob_wspolistniejacych,zgony_w_wyniku_covid_i_chorob_wspolistniejacych,liczba_zlecen_poz,liczba_ozdrowiencow,liczba_osob_objetych_kwarantanna,liczba_wykonanych_testow,liczba_testow_z_wynikiem_pozytywnym,liczba_testow_z_wynikiem_negatywnym,liczba_pozostalych_testow,teryt,stan_rekordu_na
0,Cały kraj,16878,4.40,481,138,343,22880,13290,202367,96833,19415,76168,1250,t00,2022-01-12
1,dolnośląskie,1389,4.79,29,20,9,1618,1143,16137,7045,1621,5336,88,t02,2022-01-12
2,kujawsko-pomorskie,656,3.17,21,7,14,1164,773,8221,4283,747,3491,45,t04,2022-01-12
3,lubelskie,748,3.56,29,5,24,1263,621,8383,5917,842,5047,28,t06,2022-01-12
4,lubuskie,362,3.58,17,9,8,486,247,4901,2353,418,1902,33,t08,2022-01-12
5,łódzkie,744,3.04,23,12,11,1226,899,11023,6062,887,5132,43,t10,2022-01-12
6,małopolskie,2507,7.34,51,18,33,2461,1255,23360,9829,2871,6826,132,t12,2022-01-12
7,mazowieckie,2909,5.36,70,22,48,3186,2009,35282,15259,3291,11724,244,t14,2022-01-12
8,opolskie,474,4.83,6,0,6,535,310,5840,2340,568,1739,33,t16,2022-01-12
9,podkarpackie,941,4.43,10,2,8,1241,667,10476,5031,1097,3911,23,t18,2022-01-12
10,podlaskie,280,2.38,8,0,8,556,251,3737,2142,325,1799,18,t20,2022-01-12
11,pomorskie,1114,4.75,48,8,40,1551,780,13859,6414,1312,4929,173,t22,2022-01-12
12,śląskie,2046,4.54,78,12,66,3016,1301,23314,10914,2349,8379,186,t24,2022-01-12
13,świętokrzyskie,348,2.83,14,4,10,547,304,4394,2276,394,1840,42,t26,2022-01-12
14,warmińsko-mazurskie,432,3.04,14,6,8,839,551,5916,3115,514,2577,24,t28,2022-01-12
15,wielkopolskie,1247,3.56,37,11,26,1944,1333,18124,6822,1387,5351,84,t30,2022-01-12
16,zachodniopomorskie,559,3.30,26,2,24,1211,785,9311,4427,650,3733,44,t32,2022-01-12

# Adapt govpl02.ipynb